import _xcb

MOD_MASK_SHIFT = _xcb.XCB_MOD_MASK_SHIFT
MOD_MASK_LOCK = _xcb.XCB_MOD_MASK_LOCK
MOD_MASK_CONTROL = _xcb.XCB_MOD_MASK_CONTROL
MOD_MASK_1 = _xcb.XCB_MOD_MASK_1
MOD_MASK_2 = _xcb.XCB_MOD_MASK_2
MOD_MASK_3 = _xcb.XCB_MOD_MASK_3
MOD_MASK_4 = _xcb.XCB_MOD_MASK_4
MOD_MASK_5 = _xcb.XCB_MOD_MASK_5

